language: php
php:
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

notifications:
    script:
        - "phpunit -v --coverage-text --colors=never --stderr"

after_success:
    - php vendor/bin/codacycoverage clover build/logs/clover.xml

addons:
    code_climate:
        repo_token: 75882af0fd377ca5d04aa189c62561cb7e68b46463cac7e48d3210baebd9c374