language: php
php:
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true

notifications:
    script:
        - "phpunit -v --coverage-text --colors=never --stderr"

after_success:
    - php vendor/bin/codacycoverage clover build/logs/clover.xml

addons:
    code_climate:
        repo_token: 75882af0fd377ca5d04aa189c62561cb7e68b46463cac7e48d3210baebd9c374